### ISSUE TITLE
Implement sorting

### ISSUE THREAD

**Issue by asm0dey** [f-nyx/kotlin-search#4]
There is a similarity API in Lucene: https://lucene.apache.org/core/7_0_1/core/org/apache/lucene/search/similarities/Similarity.html

It would be nice to access it in Kotlin-search too

**Comment by f-nyx** [comment]
Yes, sorting is one of the big TODOs, I'd be glad to implement it. I'll take a look at the similarity API and I'll make a proposal for the kotlin-search API.

**Comment by asm0dey** [comment]
If anything, here is the example with all the modern best practices: https://github.com/asm0dey/dummylib-multiplatform/blob/main/convention-plugins/src/main/kotlin/module.publication.gradle.kts

Here it's used for a KMP project, but the same approach can be used for JVM

**Comment by f-nyx** [comment]
@asm0dey I added support for sorting by arbitrary fields. It requires to mark fields as `DocValues`. I updated the documentation to describe the API: https://github.com/f-nyx/kotlin-search/tree/develop#sorting

If you don't have any questions,  comments or complains about it, I'll go ahead and create a new release this weekend.

Thanks for the feedback!

**Comment by asm0dey** [comment]
@f-nyx I finally had some time to look into it. I don't completely get an idea: is there a way to sort by similarity? Or will sort by field just sort the result alphabetically?
